#Hugo configuration
title = "Test"
baseURL = "https:\/\/www.test.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758367"
subfolder = ""
